services:
  mariadb:
    image: docker.io/bitnami/mariadb:11.3
    volumes:
      - mariadb_data:/bitnami/mariadb
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=${DB_USER}
      - MARIADB_DATABASE=${DB_NAME}
    restart: unless-stopped

  wordpress:
    image: docker.io/bitnami/wordpress:6
    expose:
      - 8080
      - 8443
    volumes:
      - wordpress_data:/bitnami/wordpress
    depends_on:
      - mariadb
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - WORDPRESS_DATABASE_HOST=${WORDPRESS_DATABASE_HOST}
      - WORDPRESS_DATABASE_PORT_NUMBER=${WORDPRESS_DATABASE_PORT_NUMBER}
      - WORDPRESS_DATABASE_USER=${DB_USER}
      - WORDPRESS_DATABASE_NAME=${DB_NAME}
    deploy:
      replicas: 4
    restart: unless-stopped

  nginx:
    image: nginx:latest
    ports:
      - ${HTTP_PORT}:80
      - ${HTTPS_PORT}:443
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - wordpress
    restart: unless-stopped

volumes:
  mariadb_data:
  wordpress_data: